import Img1 from './images/Ecommerce3.png';
import Img2 from './images/search1.png';
import Img3 from './images/redsapp2.png';
import Img4 from "./images/caption1.png"
import Img5 from "./images/one.jpg"


import ecommerce1 from "./images/Ecommerce1.png"
import ecommerce2 from "./images/Ecommerce2.png"
import ecommerce3 from "./images/Ecommerce3.png"
import ecommerce4 from "./images/Ecommerce4.png"
import ecommerce5 from "./images/Ecommerce5.png"

import search1 from "./images/search1.png"
import search2 from "./images/search2.png"
import search3 from "./images/search3.png"

import redsapp1 from "./images/redsapp1.png"
import redsapp2 from "./images/redsapp2.png"
import redsapp3 from "./images/redsapp3.png"
import redsapp4 from "./images/redsapp4.png"

import caption1 from "./images/caption1.png"
import caption2 from "./images/caption2.png"
import caption3 from "./images/caption3.png"

import tonny1 from "./images/tonny1.PNG"
import tonny2 from "./images/tonny2.PNG"
import tonny3 from "./images/tonny3.PNG"

import whatsApp1 from "./images/whatsapp1.png"
import whatsApp2 from "./images/whatsapp2.png"
import whatsApp3 from "./images/whatsapp3.png"
import whatsApp4 from "./images/whatsapp4.png"
import whatsApp5 from "./images/whatsapp5.png"







export default [
	{
		title:"Whatsapp-Clone",
		image:whatsApp2,
		desc:
			'This project is the clone of whatsappweb which is made using react and redux for the frontend , nodejs for the backend. All the realtime communication is made using socket.io. The project is deployed on netlify. ',
		slides:[whatsApp1 , whatsApp2 , whatsApp3 , whatsApp4 , whatsApp5]
	},
	{
		title: 'Estore',
		image: Img1,
		desc:
            'It is a fully functional E-commerce application.It uses Vue.JS in the frontend, and firebase cloud functions as the backend',
        slides:[ecommerce1,ecommerce2,ecommerce3,ecommerce4,ecommerce5]
	},
	{
		title: 'Image based Serach Engine',
		image: Img2,
		desc:
            'It is an image based Search-Engine made using python,keras and tensorflow.It predicts the top 10 results with highest probabilities with the query image',
        slides:[search1,search2,search3]
	},
	{
		title: 'Redsapp',
		image: Img3,
		desc:	'It is a fully functional twitter clone made using ReactJs as the frontend and firebase cloud functions as the backend. You can like,comment,update ,delete tweets and receive real time notifications.User can also update his profile just like a typical social media platform ',
		slides:[redsapp1,redsapp4,redsapp2 ,redsapp3]
	},
	{
		title: 'Caption-Bot',
		image: Img4,
		desc:
			'It is made using python,keras ,tensorflow,glove vectors and transfer learning using Resnet50.It analyzes the image and predict the most appropriate caption using beam search.',
		slides:[caption1,caption2,caption3]
	},
	{
		title: 'Prediction Of facial features',
		image: Img5,
		desc:
			'this projects predicts the old and young age features using tensorflow,keras and stylegans.You can see the images of tonny stark generated by the model clicking the image',
		slides:[tonny1,tonny2,tonny3]
	},

];
